version: 2.1

jobs:
  test:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all
      - run:
          name: Run clippy
          command: |
              rustup component add clippy
              cargo clippy --all -- -D warnings
      - run:
          name: Run Format
          command: |
            rustup component add rustfmt
            cargo fmt --all -- --check

  coverage:
    machine: true
    steps:
        - checkout
        - run:
            name: Coverage with docker
            command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin sh -c "cargo tarpaulin --ciserver circle-ci --coveralls $COVERALLS_REPO_TOKEN"


workflows:
  version: 2.1
  test:
    jobs:
      - test
      - coverage
